const BUILTIN_STYLE_DEFINITIONS = [
  {
    rawName: "正文",
    styleId: "1",
    styleName: "Normal",
    type: "paragraph",
    default: true,
    next: "2",
    uiPriority: "0",
    qFormat: true,
  },
  {
    rawName: "正文缩进",
    styleId: "2",
    styleName: "Normal Indent",
    type: "paragraph",
    basedOn: "1",
    uiPriority: "0",
    qFormat: true,
  },
  {
    rawName: "批注文字",
    styleId: "3",
    styleName: "annotation text",
    type: "paragraph",
    basedOn: "1",
    uiPriority: "99",
    qFormat: true,
    unhideWhenUsed: true,
  },
  {
    rawName: "纯文本",
    styleId: "4",
    styleName: "Plain Text",
    type: "paragraph",
    basedOn: "1",
    link: "13",
    uiPriority: "99",
    qFormat: true,
    unhideWhenUsed: true,
  },
  {
    rawName: "页脚",
    styleId: "5",
    styleName: "footer",
    type: "paragraph",
    basedOn: "1",
    link: "14",
    uiPriority: "0",
    qFormat: true,
  },
  {
    rawName: "页眉",
    styleId: "6",
    styleName: "header",
    type: "paragraph",
    basedOn: "1",
    link: "15",
    uiPriority: "0",
    qFormat: true,
  },
  {
    rawName: "普通(网站)",
    styleId: "7",
    styleName: "Normal (Web)",
    type: "paragraph",
    basedOn: "1",
    uiPriority: "99",
    qFormat: true,
    unhideWhenUsed: true,
  },
  {
    rawName: "普通表格",
    styleId: "8",
    styleName: "Normal Table",
    type: "table",
    default: true,
    uiPriority: "99",
    qFormat: true,
    unhideWhenUsed: true,
  },
  {
    rawName: "默认段落字体",
    styleId: "9",
    styleName: "Default Paragraph Font",
    type: "character",
    default: true,
    uiPriority: "0",
    qFormat: true,
  },
  {
    rawName: "页码",
    styleId: "10",
    styleName: "page number",
    type: "character",
    basedOn: "9",
    uiPriority: "99",
    qFormat: true,
    unhideWhenUsed: true,
  },
  {
    rawName: "超链接",
    styleId: "11",
    styleName: "Hyperlink",
    type: "character",
    uiPriority: "0",
    qFormat: true,
  },
  {
    rawName: "批注引用",
    styleId: "12",
    styleName: "annotation reference",
    type: "character",
    uiPriority: "99",
    qFormat: true,
    unhideWhenUsed: true,
  },
  {
    rawName: "纯文本 Char",
    styleId: "13",
    styleName: "纯文本 Char",
    type: "character",
    customStyle: true,
    link: "4",
    uiPriority: "99",
    qFormat: true,
  },
  {
    rawName: "页脚 Char",
    styleId: "14",
    styleName: "页脚 Char",
    type: "character",
    customStyle: true,
    link: "5",
    uiPriority: "0",
    qFormat: true,
  },
  {
    rawName: "页眉 Char",
    styleId: "15",
    styleName: "页眉 Char",
    type: "character",
    customStyle: true,
    link: "6",
    uiPriority: "0",
    qFormat: true,
  },
  {
    rawName: "段 Char",
    styleId: "16",
    styleName: "段 Char",
    type: "character",
    customStyle: true,
    uiPriority: "0",
    qFormat: true,
  },
];

const BUILTIN_STYLE_DEFINITION_BY_RAW_NAME = new Map(
  BUILTIN_STYLE_DEFINITIONS.map((definition) => [definition.rawName, definition]),
);

const BUILTIN_STYLE_DEFINITION_BY_ID = new Map(
  BUILTIN_STYLE_DEFINITIONS.map((definition) => [definition.styleId, definition]),
);

export function getBuiltInStyleDefinitionByRawName(rawName) {
  return BUILTIN_STYLE_DEFINITION_BY_RAW_NAME.get(rawName) ?? null;
}

export function getBuiltInStyleDefinitionById(styleId) {
  return BUILTIN_STYLE_DEFINITION_BY_ID.get(String(styleId)) ?? null;
}

export function resolveStyleIdFromRawName(rawName, index) {
  return getBuiltInStyleDefinitionByRawName(rawName)?.styleId ?? String(index + 1);
}

export function resolveStyleNameFromRawName(rawName) {
  return getBuiltInStyleDefinitionByRawName(rawName)?.styleName ?? rawName;
}

export function resolveStyleTypeFromSgc(rawName, sgc) {
  const builtIn = getBuiltInStyleDefinitionByRawName(rawName);
  if (builtIn) return builtIn.type;
  if (sgc === 2) return "character";
  if (sgc === 5) return "table";
  return "paragraph";
}

// Standard Word built-in style UI priorities as defined in the OOXML spec.
// Each entry: [styleName, qFormat, uiPriority]
// Styles not listed inherit the default priority (99).
const STANDARD_STYLE_PRIORITIES = [
  ["Normal", true, 0],
  ["heading 1", true, 9],
  ["heading 2", true, 9],
  ["heading 3", true, 9],
  ["heading 4", true, 9],
  ["heading 5", true, 9],
  ["heading 6", true, 9],
  ["heading 7", true, 9],
  ["heading 8", true, 9],
  ["heading 9", true, 9],
  ["index 1", false, 99],
  ["index 2", false, 99],
  ["index 3", false, 99],
  ["index 4", false, 99],
  ["index 5", false, 99],
  ["index 6", false, 99],
  ["index 7", false, 99],
  ["index 8", false, 99],
  ["index 9", false, 99],
  ["toc 1", false, 39],
  ["toc 2", false, 39],
  ["toc 3", false, 39],
  ["toc 4", false, 39],
  ["toc 5", false, 39],
  ["toc 6", false, 39],
  ["toc 7", false, 39],
  ["toc 8", false, 39],
  ["toc 9", false, 39],
  ["Normal Indent", true, 0],
  ["footnote text", false, 99],
  ["annotation text", true, 99],
  ["header", true, 0],
  ["footer", true, 0],
  ["index heading", false, 99],
  ["caption", true, 35],
  ["table of figures", false, 99],
  ["envelope address", false, 99],
  ["envelope return", false, 99],
  ["footnote reference", false, 99],
  ["annotation reference", true, 99],
  ["line number", false, 99],
  ["page number", true, 99],
  ["endnote reference", false, 99],
  ["endnote text", false, 99],
  ["table of authorities", false, 99],
  ["macro", false, 99],
  ["toa heading", false, 99],
  ["List", false, 99],
  ["List Bullet", false, 99],
  ["List Number", false, 99],
  ["List 2", false, 99],
  ["List 3", false, 99],
  ["List 4", false, 99],
  ["List 5", false, 99],
  ["List Bullet 2", false, 99],
  ["List Bullet 3", false, 99],
  ["List Bullet 4", false, 99],
  ["List Bullet 5", false, 99],
  ["List Number 2", false, 99],
  ["List Number 3", false, 99],
  ["List Number 4", false, 99],
  ["List Number 5", false, 99],
  ["Title", true, 10],
  ["Closing", false, 99],
  ["Signature", false, 99],
  ["Default Paragraph Font", true, 1],
  ["Body Text", true, 1],
  ["Body Text Indent", false, 99],
  ["List Continue", false, 99],
  ["List Continue 2", false, 99],
  ["List Continue 3", false, 99],
  ["List Continue 4", false, 99],
  ["List Continue 5", false, 99],
  ["Message Header", false, 99],
  ["Subtitle", true, 11],
  ["Salutation", false, 99],
  ["Date", false, 99],
  ["Body Text First Indent", false, 99],
  ["Body Text First Indent 2", false, 99],
  ["Note Heading", false, 99],
  ["Body Text 2", false, 99],
  ["Body Text 3", false, 99],
  ["Body Text Indent 2", false, 99],
  ["Body Text Indent 3", false, 99],
  ["Block Text", false, 99],
  ["Hyperlink", true, 0],
  ["FollowedHyperlink", false, 99],
  ["Strong", true, 22],
  ["Emphasis", true, 20],
  ["Document Map", false, 99],
  ["Plain Text", true, 99],
  ["E-mail Signature", false, 99],
  ["Normal (Web)", true, 99],
  ["HTML Acronym", false, 99],
  ["HTML Address", false, 99],
  ["HTML Cite", false, 99],
  ["HTML Code", false, 99],
  ["HTML Definition", false, 99],
  ["HTML Keyboard", false, 99],
  ["HTML Preformatted", false, 99],
  ["HTML Sample", false, 99],
  ["HTML Typewriter", false, 99],
  ["HTML Variable", false, 99],
  ["Normal Table", true, 99],
  ["annotation subject", false, 99],
  ["No Spacing", true, 1],
  ["List Paragraph", true, 1],
  ["Quote", true, 29],
  ["Intense Quote", true, 30],
  ["Subtle Reference", true, 31],
  ["Intense Reference", true, 32],
  ["Book Title", true, 33],
  ["Bibliography", true, 34],
  ["TOC Heading", true, 39],
  ["Table Grid", false, 59],
  ["Table Theme", false, 99],
  ["Light Shading", false, 60],
  ["Light List", false, 61],
  ["Light Grid", false, 62],
  ["Medium Shading 1", false, 63],
  ["Medium Shading 2", false, 64],
  ["Medium List 1", false, 65],
  ["Medium List 2", false, 66],
  ["Medium Grid 1", false, 67],
  ["Medium Grid 2", false, 68],
  ["Medium Grid 3", false, 69],
  ["Dark List", false, 70],
  ["Colorful Shading", false, 71],
  ["Colorful List", false, 72],
  ["Colorful Grid", false, 73],
  ["Light Shading Accent 1", false, 60],
  ["Light List Accent 1", false, 61],
  ["Light Grid Accent 1", false, 62],
  ["Medium Shading 1 Accent 1", false, 63],
  ["Medium Shading 2 Accent 1", false, 64],
  ["Medium List 1 Accent 1", false, 65],
  ["Medium List 2 Accent 1", false, 66],
  ["Medium Grid 1 Accent 1", false, 67],
  ["Medium Grid 2 Accent 1", false, 68],
  ["Medium Grid 3 Accent 1", false, 69],
  ["Dark List Accent 1", false, 70],
  ["Colorful Shading Accent 1", false, 71],
  ["Colorful List Accent 1", false, 72],
  ["Colorful Grid Accent 1", false, 73],
  ["Light Shading Accent 2", false, 60],
  ["Light List Accent 2", false, 61],
  ["Light Grid Accent 2", false, 62],
  ["Medium Shading 1 Accent 2", false, 63],
  ["Medium Shading 2 Accent 2", false, 64],
  ["Medium List 1 Accent 2", false, 65],
  ["Medium List 2 Accent 2", false, 66],
  ["Medium Grid 1 Accent 2", false, 67],
  ["Medium Grid 2 Accent 2", false, 68],
  ["Medium Grid 3 Accent 2", false, 69],
  ["Dark List Accent 2", false, 70],
  ["Colorful Shading Accent 2", false, 71],
  ["Colorful List Accent 2", false, 72],
  ["Colorful Grid Accent 2", false, 73],
  ["Light Shading Accent 3", false, 60],
  ["Light List Accent 3", false, 61],
  ["Light Grid Accent 3", false, 62],
  ["Medium Shading 1 Accent 3", false, 63],
  ["Medium Shading 2 Accent 3", false, 64],
  ["Medium List 1 Accent 3", false, 65],
  ["Medium List 2 Accent 3", false, 66],
  ["Medium Grid 1 Accent 3", false, 67],
  ["Medium Grid 2 Accent 3", false, 68],
  ["Medium Grid 3 Accent 3", false, 69],
  ["Dark List Accent 3", false, 70],
  ["Colorful Shading Accent 3", false, 71],
  ["Colorful List Accent 3", false, 72],
  ["Colorful Grid Accent 3", false, 73],
  ["Light Shading Accent 4", false, 60],
  ["Light List Accent 4", false, 61],
  ["Light Grid Accent 4", false, 62],
  ["Medium Shading 1 Accent 4", false, 63],
  ["Medium Shading 2 Accent 4", false, 64],
  ["Medium List 1 Accent 4", false, 65],
  ["Medium List 2 Accent 4", false, 66],
  ["Medium Grid 1 Accent 4", false, 67],
  ["Medium Grid 2 Accent 4", false, 68],
  ["Medium Grid 3 Accent 4", false, 69],
  ["Dark List Accent 4", false, 70],
  ["Colorful Shading Accent 4", false, 71],
  ["Colorful List Accent 4", false, 72],
  ["Colorful Grid Accent 4", false, 73],
  ["Light Shading Accent 5", false, 60],
  ["Light List Accent 5", false, 61],
  ["Light Grid Accent 5", false, 62],
  ["Medium Shading 1 Accent 5", false, 63],
  ["Medium Shading 2 Accent 5", false, 64],
  ["Medium List 1 Accent 5", false, 65],
  ["Medium List 2 Accent 5", false, 66],
  ["Medium Grid 1 Accent 5", false, 67],
  ["Medium Grid 2 Accent 5", false, 68],
  ["Medium Grid 3 Accent 5", false, 69],
  ["Dark List Accent 5", false, 70],
  ["Colorful Shading Accent 5", false, 71],
  ["Colorful List Accent 5", false, 72],
  ["Colorful Grid Accent 5", false, 73],
  ["Light Shading Accent 6", false, 60],
  ["Light List Accent 6", false, 61],
  ["Light Grid Accent 6", false, 62],
  ["Medium Shading 1 Accent 6", false, 63],
  ["Medium Shading 2 Accent 6", false, 64],
  ["Medium List 1 Accent 6", false, 65],
  ["Medium List 2 Accent 6", false, 66],
  ["Medium Grid 1 Accent 6", false, 67],
  ["Medium Grid 2 Accent 6", false, 68],
  ["Medium Grid 3 Accent 6", false, 69],
  ["Dark List Accent 6", false, 70],
  ["Colorful Shading Accent 6", false, 71],
  ["Colorful List Accent 6", false, 72],
  ["Colorful Grid Accent 6", false, 73],
];

export function getStandardStylePriority(styleName) {
  const entry = STANDARD_STYLE_PRIORITIES.find(([name]) => name === styleName);
  return entry ? { qFormat: entry[1], uiPriority: entry[2] } : null;
}
